version: '3.8'

services:
  db:
    image: postgres:15
    container_name: compra-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: compra_user
      POSTGRES_PASSWORD: compra_pass
      POSTGRES_DB: compra_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U compra_user -d compra_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: ./backend/NewProject-API  # Ruta a tu Dockerfile
    container_name: compra-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/compra_db
      SPRING_DATASOURCE_USERNAME: compra_user
      SPRING_DATASOURCE_PASSWORD: compra_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy