version: '3.8'

services:
  db:
    image: postgres:15
    container_name: compra-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: compra_user
      POSTGRES_PASSWORD: compra_pass
      POSTGRES_DB: compra_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data