services:
  db:
    image: postgres:15
    container_name: compra-db-desarrollo
    restart: unless-stopped
    environment:
      POSTGRES_USER: compra_user
      POSTGRES_PASSWORD: compra_pass
      POSTGRES_DB: compra_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  
# In case of emergency, run this docker-compose, it contains the container for development in local